name: Validate & What-If (Bicep)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validate-and-whatif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set subscription
        run: az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Validate & What-If for all parameter files
        shell: bash
        env:
          RG: ${{ secrets.AZURE_RESOURCE_GROUP }}
        run: |
          set -euo pipefail
          shopt -s nullglob
          for f in parameters/*.json; do
            echo "::group::VALIDATE $f"
            az deployment group validate                   --resource-group "$RG"                   --template-file templates/azure-deploy.bicep                   --parameters @"$f"
            echo "::endgroup::"

            echo "::group::WHAT-IF $f"
            az deployment group what-if                   --resource-group "$RG"                   --template-file templates/azure-deploy.bicep                   --parameters @"$f"                   --no-pretty-print
            echo "::endgroup::"
          done
